### ISSUE TITLE
/APP/agent/<identifier>/  does not serve or expect valid Atom format

### ISSUE THREAD

**Issue by ldko** [unt-libraries/django-premis-event-service#1]
Currently /APP/agent/`<identifier>`/ does not work with valid Atom. A GET request gives you this:

```
<?xml version="1.0"?>
<premis:agent xmlns:premis="info:lc/xmlns/premis-v2">
  <premis:agentIdentifier>
    <premis:agentIdentifierValue>codaIngest</premis:agentIdentifierValue>
    <premis:agentIdentifierType>UNTL:Agent</premis:agentIdentifierType>
  </premis:agentIdentifier>
  <premis:agentName>Coda Ingest Agent</premis:agentName>
  <premis:agentType>Software</premis:agentType>
</premis:agent>
```

when the `<premis:agent>` stuff should be inside the `<content>` of an Atom `<entry>`. POST and PUT requests also are expecting the above invalid format.

Currently POST can "overwrite" a document with the same identifier. Is this supposed to be allowed?

**Comment by runderwood** [comment]
This is in e89e2f (on unt-libraries/django-premis-event-service@premis-v2-validation a.t.m.)
