### ISSUE TITLE
readthedocs documentation is out of date

### ISSUE THREAD

**Issue by kieranjol** [unt-libraries/django-premis-event-service#112]
The readthedocs links are the first thing that comes up on a google search for 'premis event service', but the docs haven't been updated alongside the README.rst. Some of the main things are noting python3 support along with newer Django.

**Comment by kieranjol** [comment]
Actually, it looks like your documentation is up to date in this repo, but it appears that readthedocs isn't automatically building against git master, so things are out of date there?

**Comment by ldko** [comment]
Hi Kieran, thanks for pointing this out :1st_place_medal: . I have updated the Read the Docs for the project and set it to trigger automatically.

**Comment by kieranjol** [comment]
Thanks so much!
