### ISSUE TITLE
missing author for valid Atom

### ISSUE THREAD

**Issue by ldko** [unt-libraries/django-premis-event-service#2]
The event and agent feeds and entries need to have an author element to be valid Atom.
Need authors at:
/APP/event/
/APP/agent/
/APP/event/87bf2dcc7af14c78a4dd614ad1c11210/
/APP/agent/codaIngest/

**Comment by runderwood** [comment]
Atom spec says author field should be a `person construct`, allowing for a `name`, `email`, and `uri`. What do we want for these? @ldko

**Comment by ldko** [comment]
I think we have been using what is in [this](https://github.com/unt-libraries/codalib/blob/master/codalib/__init__.py). Is an email required?

**Comment by runderwood** [comment]
No, `uri` and `email` are allowed but not required. I think only `name` is mandatory.

I'll use the same thing that's in `codalib`.
