### ISSUE TITLE
swap lxml with python xml standard library

### ISSUE THREAD

**Issue by ldko** [unt-libraries/django-premis-event-service#3]
We may want to rework things to use the standard library rather than using the third party lxml variation that  has system dependencies.

**Comment by damonkelley** [comment]
I don't think this is going to be a simple as swapping the two. The tests also depend on `lxml.objectify`, and the standard library does not have anything comparable. 

We have talked about moving the XML related functionality to some custom serializers. Doing so will likely remove the lxml dependency.

I am going to close this for now.
