### ISSUE TITLE
Create valid PREMIS output

### ISSUE THREAD

**Issue by somexpert** [unt-libraries/django-premis-event-service#4]
The premis events being created are not compliant with the v2 premis schema. The three basic steps to compliance are:
1. eventDateTime needs to replace the space that separated the date and time with a 'T'. For instance, "2015-06-05 20:35:40" needs to become "2015-06-05T20:35:40".
2. eventOutcomeDetail needs to move its content to a subelement called eventOutcomeDetailNote.
3. Everything needs to be re-ordered to comply with [this schema](http://www.loc.gov/standards/premis/v2/premis-v2-0.xsd)

**Comment by vphill** [comment]
We will need to verify that the PREMIS parsing code works with "valid" PREMIS XML
