### ISSUE TITLE
/agent/<identifier>.xml is not Atom like button says

### ISSUE THREAD

**Issue by ldko** [unt-libraries/django-premis-event-service#5]
agent.html template for /agent/`<identifier>`/ displays a button labeled "XML/ATOM" that links to /agent/`<identifier>`.premis.xml which is not valid Atom. Should that button take the user to /APP/agent/`identifier`/ similar to the button on an event entry page? If so, should it use a similarly labeled button? Or is that template served as desired and we should change the label on the button?

**Comment by ldko** [comment]
@vphill can you look at the questions here when you get a chance?

**Comment by vphill** [comment]
I think we should make it consistent with the behavior of other parts of the app and lead us to /APP/agent/`identifier`/ and it should return the ATOM wrapped version.

**Comment by ldko** [comment]
I think this issue still needs some handling. We should change the button on /agent/`identifier`/ view to look like the "Atompub" button on the /event/`identifier`/ view  and then link the button to /APP/agent/`identifier`/ rather than where it goes now.

**Comment by runderwood** [comment]
Should we keep the button that's there now and change its label to XML (in addition to adding the Atompub button)?

Also, should there be a JSON representation of both?

**Comment by ldko** [comment]
I am not sure what led to the decision to have the premis.xml and JSON formats of agent and not event. The way things are in the app, I am fine with keeping an XML button on agent and not adding a JSON representation to event. Though @vphill may want different, since of any of us, he is the one that might know why we have the different representations.
