### ISSUE TITLE
Event Search Unusable at Scale

### ISSUE THREAD

**Issue by runderwood** [unt-libraries/django-premis-event-service#68]
The unoptimized queries generated by the Django ORM are too slow for a responsive search facility.

This is complicated by the schema. We're using large keys, and when the event table reaches >10M rows, paging through these entries becomes impossible, as each query does a scan over the previous N rows to reach the offset. It would be simple to alter the table to include a non-primary key auto_increment field, an ordinal to use for paging. But that's not simple with Django's ORM. It's actually impossible to create a migration with a field that is auto_increment *and* not a primary key.

So I'm trying to find a solution that doesn't require `ALTER` operations on a table with ~15M rows. That will likely involve using `event_added` in a `where` clause to speed up scans in paged queries.

**Comment by runderwood** [comment]
@ldko Is there some (strong) preference for ordering in event search?

**Comment by ldko** [comment]
I believe it should be date descending. @vphill

**Comment by vphill** [comment]
I think that makes the most sense for the app.

**Comment by runderwood** [comment]
Then I'll likely try to fix paging by using the `event_added` value as an ordinal. I think including that last record on a page in the "next" link will let me build a where clause that prevents full-table scans over 13M+ rows.

**Comment by runderwood** [comment]
@vphill For clarity, when you say date descending do you prefer the date the event is *added* or the date in the event *payload*? We store and index both. I think, in practice, they're usually very close together. But they aren't exactly the same thing. I can use either, I think.

**Comment by vphill** [comment]
To pick one I think that ordered by _added_ would make sense the most.  But I'm not 100% committed to that answer.

**Comment by runderwood** [comment]
So this indexing thing actually doesn't solve the problem. And I can't use the `event_added` date for paging because it is non-unique. I think the best thing might be to add a sequence column to the table, an `auto_increment` field, but leave the primary key alone. We can populate existing rows' sequence fields in the order they were added (by the `event_added` column) then use that for ordering and offsets.

**Comment by runderwood** [comment]
Add the column (~20 mins.):

    alter table premis_event_service_event add column ordinal int not null;

Create variable:

    set @ord = 0;

Set each row, incrementing the ordinal working back from earliest extant event (? mins.):

    update premis_event_service_event set ordinal = (@ord:=@ord+1) order by event_added asc, event_identifier desc;

Add index on the new column:

    alter table premis_event_service_event add index premis_event_service_event_ordinal_xxxxxxxx (ordinal);

Make it `auto_increment`:

    alter table premis_event_service_event change ordinal ordinal int not null auto_increment;

**Comment by runderwood** [comment]
So, using ordinals as described above works for unfiltered queries. That means you can page through events ordered by date added through all 650,000+ pages without ten minute queries.

Unfortunately, Django's ORM disallows non-PK Auto fields, which complicates things. But I'm testing -- slowly -- custom migrations to do the above as cleanly as possible within the rules of the ORM and migrations.

As things are now, I think this will break compatibility with sqlite and other DB backends.

**Comment by runderwood** [comment]
This seems to be fixed, and the changes work with SQLite just fine, by all appearances.
