### ISSUE TITLE
Post an event - 500 Internal Server Error

### ISSUE THREAD

**Issue by mchoeti** [unt-libraries/django-premis-event-service#78]
Hi again, finally the environment is working and now i have some questions abot the API. The Get requests for the REST API are working. As example my self created agent1 is available
[http://127.0.0.1:8000/APP/agent/agent1)](http://127.0.0.1:8000/APP/agent/agent1) . 
Now I want to create an example event. For that I followed the guide. [http://premis-event-service.readthedocs.io/en/latest/api.html#example](http://premis-event-service.readthedocs.io/en/latest/api.html#example) 
Not sure why you are using different premis versions but I think this is a mismatch in the documentation. I added the sample xml file in the content section, but unfortunately the answer is an 500 INTERNAL SERVER Error. Hers is my example which I want to post on [http://127.0.0.1:8000/APP/event](http://127.0.0.1:8000/APP/event)

```
<?xml version="1.0" encoding="UTF-8"?>
<entry xmlns="http://www.w3.org/2005/Atom">
    <title>PREMIS event entry for object_123</title>
    <id>firstEvent</id>
    <updated>2011-­‐01-­‐27T16:40:30Z</updated>
    <author>
        <name>Object Verification Script</name>
    </author>
    <content type="application/xml">
            <premis:event xmlns:premis="info:lc/xmlns/premis-v2">
                <premis:eventType>
                    validateObject
                </premis:eventType>
                <premis:linkingAgentIdentifier>
                    <premis:linkingAgentIdentifierValue>
                        validateObjectScript
                    </premis:linkingAgentIdentifierValue>
                    <premis:linkingAgentIdentifierType>
                        Program
                    </premis:linkingAgentIdentifierType>
                </premis:linkingAgentIdentifier>
                <premis:eventIdentifier>
                    <premis:eventIdentifierType>
                        TEMP
                    </premis:eventIdentifierType>
                    <premis:eventIdentifierValue>
                        TEMP
                    </premis:eventIdentifierValue>
                </premis:eventIdentifier>
                <premis:eventDetail>Validation of object
                    object_123
                </premis:eventDetail>
                <premis:eventOutcomeInformation>
                    <premis:eventOutcomeDetail>
                        Generated sum for object_123/data/pic_002.tif does not match stored value
                    </premis:eventOutcomeDetail>
                    <premis:eventOutcome>
                        Failure
                    </premis:eventOutcome>
                </premis:eventOutcomeInformation>
                <premis:eventDateTime>
                    2011-01-27 16:39:49
                </premis:eventDateTime>
                <premis:linkingObjectIdentifier>
                    <premis:linkingObjectIdentifierType>
                        Local Identifier
                    </premis:linkingObjectIdentifierType>
                    <premis:linkingObjectIdentifierValue>
                        object_123
                    </premis:linkingObjectIdentifierValue>
                    <premis:linkingObjectRole />
                </premis:linkingObjectIdentifier>
            </premis:event>        
    </content>
</entry>
```

I am wondering if there is more documentation about your REST API, would be nice if you could shre more information about that.

**Comment by runderwood** [comment]
@mchoeti Two of your datetimes are invalid. There are bad characters in the first instance. In the second, `2011-01-27 16:39:49`, there ought to be a `T`, like so: `2011-01-27T16:39:49` (as produced by `datetime.isoformat`).

**Comment by ldko** [comment]
@mchoeti, we have done some work on the service since those examples were included in the docs. We need to update those. Fixing the dates should work to allow you to POST your event as @runderwood  indicates. However, I don't think that example PREMIS block in the docs is actually valid. Until we get the docs updated, you could look at https://github.com/unt-libraries/django-premis-event-service/blob/master/tests/conftest.py for better examples of what the valid PREMIS should be--if you use the old version in the docs, some of the information POSTed won't be stored.

**Comment by mchoeti** [comment]
HI, @runderwood  @ldko thanks for the help. This is one example which is working, you could add this to your doc. thanks

Post http://127.0.0.1:8000/APP/event/

```
<?xml version="1.0" encoding="UTF-8"?>
<entry xmlns="http://www.w3.org/2005/Atom">
    <title>PREMIS event entry for object_123</title>
    <id>firstEvent</id>
    <updated>2017-03-07T16:39:49</updated>
    <author>
        <name>Object Verification Script</name>
    </author>
    <content type="application/xml">
        <premis:event xmlns:premis="http://www.loc.gov/premis/v2">
            <premis:eventType>Validate</premis:eventType>
            <premis:linkingAgentIdentifier>
                <premis:linkingAgentIdentifierValue>agent1</premis:linkingAgentIdentifierValue>
                <premis:linkingAgentIdentifierType>Human</premis:linkingAgentIdentifierType>
            </premis:linkingAgentIdentifier>
            <premis:eventIdentifier>
                <premis:eventIdentifierType>TEMP</premis:eventIdentifierType>
                <premis:eventIdentifierValue>TEMP</premis:eventIdentifierValue>
            </premis:eventIdentifier>
            <premis:eventDetail>Validation of object object_123</premis:eventDetail>
            <premis:eventOutcomeInformation>
                <premis:eventOutcomeDetail>Only a detail</premis:eventOutcomeDetail>
                <premis:eventOutcome>Sucess</premis:eventOutcome>
            </premis:eventOutcomeInformation>
            <premis:eventDateTime>2017-03-09T16:39:49</premis:eventDateTime>
            <premis:linkingObjectIdentifier>
                <premis:linkingObjectIdentifierType>Linking Local</premis:linkingObjectIdentifierType>
                <premis:linkingObjectIdentifierValue>object_card</premis:linkingObjectIdentifierValue>
                <premis:linkingObjectRole />
            </premis:linkingObjectIdentifier>
        </premis:event>
    </content>
</entry>

```
It is true that i got a 201, but do not worry, it is all i need at the moment. Thanks for your help. Let me know @ldko are you also planning to associate with PREMIS v3. Cheers and good night..

**Comment by runderwood** [comment]
@mchoeti A [201 is the correct response](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#2xx_Success) to the POSTing of a new document.

We're validating against v2.3 of the PREMIS schema. I don't know of plans to move to v3.0, but there aren't many significant differences. Nor are there any changes in 3.0 that apply to our use cases at the moment. Do you have specific applications for v3.0 (versus 2.3)?
