### ISSUE TITLE
For Atom entry add <link> elements where rel="alternate"

### ISSUE THREAD

**Issue by ldko** [unt-libraries/django-premis-event-service#8]
For entry Atom XML, we should add a `<link>` element with rel="alternate" that links to the HTML version of the entry.

So, in `http://example.com/APP/event/c7dc0058-99b9-482e-8f71-1f463d2295a9/` we should have a `<link href="http://example.com/event/c7dc0058-99b9-482e-8f71-1f463d2295a9/" rel="alternate"/>`.

This should be done at:
`/APP/event/<id>/`
`/APP/agent/<id>/`

**Comment by damonkelley** [comment]
This is related to unt-libraries/codalib#12 I believe
