### ISSUE TITLE
Converting event XML to object fails without some elements

### ISSUE THREAD

**Issue by ldko** [unt-libraries/django-premis-event-service#80]
[premisEventXMLToObject](https://github.com/unt-libraries/django-premis-event-service/blob/6fce3fb71c45cfcdad5c2fb561b39118c95ebabb/premis_event_service/presentation.py#L67), may error if the XML passed does not contain some non-required elements.

**Comment by runderwood** [comment]
Sorry, but this should have been moved from the `translateDict` approach to XPATH mapping along with the `agent` stuff.

I really feel like I failed to merge a feature branch in at some point. In any case, let me know if you want me to do cleanup here (that I should have already done w/ the previous work).
