### ISSUE TITLE
Increase max_length for linked_object_id in EventSearchForm

### ISSUE THREAD

**Issue by ldko** [unt-libraries/django-premis-event-service#84]
Our current ids are up to 20 chars with the ARK prefix. We need to bump [this](https://github.com/unt-libraries/django-premis-event-service/blob/37462bbdcc96cb29b1c78d011c1ede432ba3bf4f/premis_event_service/forms.py#L30) up.

**Comment by runderwood** [comment]
Is 64 bytes ok?

**Comment by ldko** [comment]
sounds ok to me
