### ISSUE TITLE
Increase EVENT_SEARCH_PER_PAGE

### ISSUE THREAD

**Issue by ldko** [unt-libraries/django-premis-event-service#85]
We are going to increase [EVENT_SEARCH_PER_PAGE](https://github.com/unt-libraries/django-premis-event-service/blob/37462bbdcc96cb29b1c78d011c1ede432ba3bf4f/premis_event_service/views.py#L34). Maybe 200?

**Comment by runderwood** [comment]
That's the desired default for event search everywhere? Or just in JSON results?

**Comment by ldko** [comment]
200 is fine for the json and html results (per @vphill )
