### ISSUE TITLE
/APP/event allows event updates with POST request

### ISSUE THREAD

**Issue by ldko** [unt-libraries/django-premis-event-service#9]
POST should create a new event only (PUT is used for updates).

**Comment by runderwood** [comment]
@ldko The logic isn't clear here. The code seems to assume that the desired behavior is to *assign* new identifiers to events POSTed with duplicate non-UUID identifiers.

The RESTful thing here seems to me to just reject conflicting identifiers. To do more seems like magic, and a 409 should tell a client enough to generate a new identifier and try again.

Another option is to provide a UUID service to clients, I suppose. What's the desired behavior?
